language: node_js
language: node_js
node_js: "12"
services:
  - docker
install:
  - npm install
  - npm install -g codecov
script:
  - "npm run test:unit:travis"
  - "npm run build"
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  - CODECOV_TOKEN="83d8b72d-1645-4184-990c-fe18f85a6314"